enum types{
    "SELECTED_PRODUCT" = "SELECTED_PRODUCT",
    "SET_PRODUCT_REQUESTED" = "SET_PRODUCT_REQUESTED",
    "SET_PRODUCT_SUCCESS" = "SET_PRODUCT_SUCCESS",
    "SET_PRODUCT_FALIED" = "SET_PRODUCT_FALIED",
    "UPDATE_PRODUCT_REQUESTED" = "UPDATE_PRODUCT_REQUESTED",
    "UPDATE_PRODUCT_SUCCESS" = "UPDATE_PRODUCT_SUCCESS",
    "UPDATE_PRODUCT_FALIED" = "UPDATE_PRODUCT_FALIED",
    "DELETE_PRODUCT_REQUESTED" = "DELETE_PRODUCT_REQUESTED",
    "DELETE_PRODUCT_SUCCESS" = "DELETE_PRODUCT_SUCCESS",
    "DELETE_PRODUCT_FALIED" = "DELETE_PRODUCT_FALIED",
    "GET_PRODUCTS_SUCCESS" = "GET_PRODUCTS_SUCCESS",
    "GET_PRODUCTS_FALIED" = "GET_PRODUCTS_FALIED",
    "GET_PRODUCTS_REQUESTED" = "GET_PRODUCTS_REQUESTED"
}
export default types